SchoolSystem.web/Areas/Admin/Controllers/BodyController.cs
using SchoolSystem.Core;
using SchoolSystem.Core.VM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolSystem.web.Areas.Admin.Controllers
{
    public class BodyController : Controller
    {
        // GET: Admin/Body
        public ActionResult Index1()
        {
            return View();
        }

        public ActionResult Search()
        {

            var model = "SP_GetAllBody".ExecuParamsSqlOrStored(false).AsList<BodyVM>();
            return View(model);
        }


        public ActionResult Create()
        {
            BodyVM Obj = new BodyVM();
            return PartialView("~/Areas/Admin/Views/Body/Create.cshtml", Obj);
        }
        [HttpPost]
        public JsonResult Create(BodyVM model)
        {
          

            var data = "SP_AddBody".ExecuParamsSqlOrStored(false, "Title".KVP(model.Title), "Details".KVP(model.Details),
                "visable".KVP(model.visable), "main".KVP(model.main), "type".KVP(model.type), "Id".KVP(model.Id)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "تم الحفظ بنجاح", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + "لم يتم الحفظ ", JsonRequestBehavior.AllowGet);
        }


        public ActionResult Edit(int id = 0)
        {
            var model = "SP_SelectBodyById".ExecuParamsSqlOrStored(false, "Id".KVP(id)).AsList<BodyVM>();
            if (model == null)
            {
                return HttpNotFound();
            }
            return View("Create", model.FirstOrDefault());
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            BodyVM obj = new BodyVM();
            obj.Id = id;
            return PartialView("~/Areas/Admin/Views/Body/Delete.cshtml", obj);
        }


        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            var data = "SP_DeleteBody".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "تم الحذف بنجاح", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + "لم يتم الحذف", JsonRequestBehavior.AllowGet);
        }
    }
}

SchoolSystem.web/Areas/Admin/Controllers/GameController.cs
using SchoolSystem.Core;
using SchoolSystem.Core.VM;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolSystem.web.Areas.Admin.Controllers
{
    public class GameController : Controller
    {
        // GET: Admin/Game
        public ActionResult Index1()
        {
            return View();
        }

        public ActionResult Search()
        {

            var model = "SP_GetAllGame".ExecuParamsSqlOrStored(false).AsList<GameVM>();
            return View(model);
        }


        public ActionResult Create()
        {
            GameVM Obj = new GameVM();

            
            return PartialView("~/Areas/Admin/Views/Game/Create.cshtml", Obj);
        }
        [HttpPost]
        public JsonResult Create(GameVM model)
        {

            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileNameWithExtension = Path.GetFileName(file.FileName);
                    var fileNameOnly = Path.GetFileNameWithoutExtension(file.FileName);
                    string RootPath = Server.MapPath("~/Images/");
                    if (!Directory.Exists(RootPath))
                    {
                        Directory.CreateDirectory(RootPath);
                    }
                    var unique = new Guid();
                    var path = Path.Combine(RootPath, fileNameOnly + unique + Path.GetExtension(file.FileName));
                    file.SaveAs(path);
                    model.GameImage = "Images/" + fileNameOnly + unique + Path.GetExtension(file.FileName);

                }




            }
            model.EngName = model.ARName;
            var data = "SP_AddGame".ExecuParamsSqlOrStored(false, "ARName".KVP(model.ARName),
                "EngName".KVP(model.EngName), "GameImage".KVP(model.GameImage), "GameURL".KVP(model.GameURL)
                 , "ID".KVP(model.GameId)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "تم الحفظ بنجاح", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + "لم يتم الحفظ ", JsonRequestBehavior.AllowGet);
        }


        public ActionResult Edit(int id = 0)
        {
            var model = "SP_SelectGameById".ExecuParamsSqlOrStored(false, "ID".KVP(id)).AsList<GameVM>();
            var lst = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
           
            if (model == null)
            {
                return HttpNotFound();
            }

            return View("Create", model.FirstOrDefault());
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            TestVM obj = new TestVM();
            obj.ID = id;
            return PartialView("~/Areas/Admin/Views/Test/Delete.cshtml", obj);
        }


        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            var data = "SP_DeleteGame".ExecuParamsSqlOrStored(false, "ID".KVP(Id)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "تم الحذف بنجاح", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + "لم يتم الحذف", JsonRequestBehavior.AllowGet);
        }
    }
}

SchoolSystem.web/Areas/Admin/Controllers/ImageController.cs
using SchoolSystem.Core;
using SchoolSystem.Core.VM;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolSystem.web.Areas.Admin.Controllers
{
    public class ImageController : Controller
    {
        // GET: Admin/Image
        public ActionResult Index1()
        {
            return View();
        }

        public ActionResult Search()
        {

            var model = "SP_GetAllImage".ExecuParamsSqlOrStored(false).AsList<ImageVM>();
            return View(model);
        }


        public ActionResult Create()
        {
            ImageVM Obj = new ImageVM();
            return PartialView("~/Areas/Admin/Views/Image/Create.cshtml", Obj);
        }
        [HttpPost]
        public JsonResult Create(ImageVM model)
        {
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileNameWithExtension = Path.GetFileName(file.FileName);
                    var fileNameOnly = Path.GetFileNameWithoutExtension(file.FileName);
                    string RootPath = Server.MapPath("~/Images/");
                    if (!Directory.Exists(RootPath))
                    {
                        Directory.CreateDirectory(RootPath);
                    }
                    var unique = new Guid();
                    var path = Path.Combine(RootPath, fileNameOnly + unique + Path.GetExtension(file.FileName));
                    file.SaveAs(path);
                    model.photo = "Images/" + fileNameOnly + unique + Path.GetExtension(file.FileName);

                }



            }

            var data = "SP_AddImage".ExecuParamsSqlOrStored(false, "Name".KVP(model.Name), "photo".KVP(model.photo),
               "ImageID".KVP(model.ImageID)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "تم الحفظ بنجاح", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + "لم يتم الحفظ ", JsonRequestBehavior.AllowGet);
        }


        public ActionResult Edit(int id = 0)
        {
            var model = "SP_SelectImageById".ExecuParamsSqlOrStored(false, "ID".KVP(id)).AsList<ImageVM>();
            if (model == null)
            {
                return HttpNotFound();
            }
            return View("Create", model.FirstOrDefault());
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            ImageVM obj = new ImageVM();
            obj.ImageID = id;
            return PartialView("~/Areas/Admin/Views/Image/Delete.cshtml", obj);
        }


        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            var data = "SP_DeleteImage".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "تم الحذف بنجاح", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + "لم يتم الحذف", JsonRequestBehavior.AllowGet);
        }
    }
}

SchoolSystem.web/Areas/Admin/Controllers/TestController.cs
using SchoolSystem.Core;
using SchoolSystem.Core.VM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolSystem.web.Areas.Admin.Controllers
{
    public class TestController : Controller
    {
        public ActionResult Index1()
        {
            return View();
        }

        public ActionResult Search()
        {

            var model = "SP_GetAllTest".ExecuParamsSqlOrStored(false).AsList<TestVM>();
            return View(model);
        }


        public ActionResult Create()
        {
            TestVM Obj = new TestVM();
            return PartialView("~/Areas/Admin/Views/Test/Create.cshtml", Obj);
        }
        [HttpPost]
        public JsonResult Create(TestVM model)
        {
            var data = "SP_AddTest".ExecuParamsSqlOrStored(false, "Title".KVP(model.Title), "IsAvilable".KVP(model.IsAvilable)
                , "CreateDate".KVP(model.CreateDate), "ID".KVP(model.ID)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "تم الحفظ بنجاح", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + "لم يتم الحفظ ", JsonRequestBehavior.AllowGet);
        }


        public ActionResult Edit(int id = 0)
        {
            var model = "SP_SelectTestById".ExecuParamsSqlOrStored(false, "ID".KVP(id)).AsList<TestVM>();
            if (model == null)
            {
                return HttpNotFound();
            }

            return View("Create", model.FirstOrDefault());
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            TestVM obj = new TestVM();
            obj.ID = id;
            return PartialView("~/Areas/Admin/Views/Test/Delete.cshtml", obj);
        }


        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            var data = "SP_DeleteTest".ExecuParamsSqlOrStored(false, "ID".KVP(Id)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "تم الحذف بنجاح", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + "لم يتم الحذف", JsonRequestBehavior.AllowGet);
        }
    }
}

SchoolSystem.web/Views/Shared/_SideMenu.cshtml
<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <!--- Divider -->
        <div id="sidebar-menu">
            <ul>
                <li class="menu-title">@SchoolSystem.Localiztion.AgentResource.Main</li>

                @*<li>
            <a href="@Url.Action("Index", "Home", new { area = "" })" class="waves-effect waves-primary">
                <i class="ti-home"></i><span>@GlobalRes.MainPage</span>
            </a>
        </li>*@

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect waves-primary">
                        <i class="ti-paint-bucket"></i> <span> @SchoolSystem.Localiztion.AgentResource.DashBoard </span>
                        <span class="menu-arrow"></span>
                    </a>
                    <ul class="list-unstyled">
                        <li><a href="@Url.Action("Index1", "MainPage", new { area = "Admin" })">@SchoolSystem.Localiztion.AgentResource.MainPage</a></li>
                        <li><a href="@Url.Action("Index1", "Body", new { area = "Admin" })">@SchoolSystem.Localiztion.AgentResource.Goalsandvision</a></li>
                        <li><a href="@Url.Action("Index1", "MNews", new { area = "Admin" })">@SchoolSystem.Localiztion.AgentResource.News</a></li>
                        <li><a href="@Url.Action("Index1", "Mservices", new { area = "Admin" })">@SchoolSystem.Localiztion.AgentResource.Services</a></li>
                        <li><a href="@Url.Action("Index1", "MCareers", new { area = "Admin" })">@SchoolSystem.Localiztion.AgentResource.Jobs</a></li>

                        <li><a href="@Url.Action("Index1", "MMagazine", new { area = "Admin" })">@SchoolSystem.Localiztion.AgentResource.MagazienMain</a></li>

                        <li><a href="@Url.Action("Index1", "Counters", new { area = "Admin" })">@SchoolSystem.Localiztion.AgentResource.Counters</a></li>
                        <li><a href="@Url.Action("Index1", "SocialMedia", new { area = "Admin" })">@SchoolSystem.Localiztion.AgentResource.SocialMedia</a></li>
                        <li><a href="@Url.Action("Index1", "Agents", new { area = "Admin" })">@SchoolSystem.Localiztion.AgentResource.Agents</a></li>
                        <li><a href="@Url.Action("Index1", "ClassGroups", new { area = "Admin" })">@SchoolSystem.Localiztion.AgentResource.Educationalforums</a></li>
                        <li><a href="@Url.Action("Index1", "Image", new { area = "Admin" })">@SchoolSystem.Localiztion.AgentResource.Images</a></li>
                    </ul>
                </li>
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect waves-primary">
                        <i class="ti-paint-bucket"></i> <span> @SchoolSystem.Localiztion.AgentResource.ExameControle </span>
                        <span class="menu-arrow"></span>
                    </a>
                    <ul class="list-unstyled">
                        <li><a href="@Url.Action("Index1", "Memory_Pattern_Answers", new { area = "Admin" })">@SchoolSystem.Localiztion.AgentResource.MemoryTestAnswers</a></li>
                        <li><a href="@Url.Action("Index1", "Memory_Pattern_Qustions", new { area = "Admin" })">@SchoolSystem.Localiztion.AgentResource.TestAnswers</a></li>
                        <li><a href="@Url.Action("Index1", "Memory_pattern_AnswerMean", new { area = "Admin" })">@SchoolSystem.Localiztion.AgentResource.memoryquestions</a></li>
                        <li><a href="@Url.Action("Index1", "memory_pattern_Test", new { area = "Admin" })">@SchoolSystem.Localiztion.AgentResource.Testthememorypattern</a></li>
                        <li><a href="@Url.Action("Index1", "Test", new { area = "Admin" })">@SchoolSystem.Localiztion.AgentResource.Aptitudetest</a></li>

                        <li><a href="@Url.Action("Index1", "Capabilitiesqustions", new { area = "Admin" })">@SchoolSystem.Localiztion.AgentResource.CapacityTestQuestions</a></li>

                        <li><a href="@Url.Action("Index1", "Game", new { area = "Admin" })">@SchoolSystem.Localiztion.AgentResource.Gamesforthegiftedchild</a></li>
                        
                    </ul>
                </li>

                @*<li class="has_sub">
            <a href="javascript:void(0);" class="waves-effect waves-primary">
                <i class="ti-paint-bucket"></i> <span> @GlobalRes.Marketing  </span>
                <span class="menu-arrow"></span>
            </a>
            <ul class="list-unstyled">
                <li><a href="@Url.Action("Index1", "ManageRequest", new { area = "Marketing" })">@GlobalRes.Order</a></li>
            </ul>
        </li>
        <li class="has_sub">
            <a href="javascript:void(0);" class="waves-effect waves-primary">
                <i class="ti-paint-bucket"></i> <span> @GlobalRes.PriceOffers  </span>
                <span class="menu-arrow"></span>
            </a>
            <ul class="list-unstyled">
                <li><a href="@Url.Action("Index1", "ManageRequestOffer", new { area = "Marketing" })">@GlobalRes.OrderInput</a></li>

            </ul>
        </li>
        <li class="has_sub">
            <a href="javascript:void(0);" class="waves-effect waves-primary">
                <i class="ti-paint-bucket"></i> <span> @GlobalRes.Contracts  </span>
                <span class="menu-arrow"></span>
            </a>
            <ul class="list-unstyled">
                <li><a href="@Url.Action("Index1", "ManageRequestContract", new { area = "Marketing" })">@GlobalRes.Contracts @Model.</a></li>

            </ul>
        </li>*@
                @*<li class="has_sub">
            <a href="javascript:void(0);" class="waves-effect waves-primary">
                <i class="ti-paint-bucket"></i> <span> @GlobalRes.Analysis  </span>
                <span class="menu-arrow"></span>
            </a>
            <ul class="list-unstyled"></ul>
        </li>

        <li class="has_sub">
            <a href="javascript:void(0);" class="waves-effect waves-primary">
                <i class="ti-paint-bucket"></i> <span> @GlobalRes.Running  </span>
                <span class="menu-arrow"></span>
            </a>
            <ul class="list-unstyled"></ul>
        </li>

        <li class="has_sub">
            <a href="javascript:void(0);" class="waves-effect waves-primary">
                <i class="ti-paint-bucket"></i> <span> @GlobalRes.SupportRequests  </span>
                <span class="menu-arrow"></span>
            </a>
            <ul class="list-unstyled"></ul>
        </li>

        <li class="has_sub">
            <a href="javascript:void(0);" class="waves-effect waves-primary">
                <i class="ti-paint-bucket"></i> <span> @GlobalRes.Engineers  </span>
                <span class="menu-arrow"></span>
            </a>
            <ul class="list-unstyled"></ul>
        </li>

        <li class="has_sub">
            <a href="javascript:void(0);" class="waves-effect waves-primary">
                <i class="ti-paint-bucket"></i> <span> @GlobalRes.Visits  </span>
                <span class="menu-arrow"></span>
            </a>
            <ul class="list-unstyled"></ul>
        </li>*@

            </ul>

            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>