SchoolSystem.web/Areas/Admin/Controllers/MNewsController.cs
using SchoolSystem.Core;
using SchoolSystem.Core.VM;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolSystem.web.Areas.Admin.Controllers
{
    public class MNewsController : Controller
    {
        // GET: Admin/MNews
        public ActionResult Index1()
        {
            return View();
        }

        public ActionResult Search()
        {

            var model = "SP_GetAllNews".ExecuParamsSqlOrStored(false).AsList<MainPageVM>();
            return View(model);
        }


        public ActionResult Create()
        {
            MainPageVM Obj = new MainPageVM();
            return PartialView("~/Areas/Admin/Views/MNews/Create.cshtml", Obj);
        }
        [HttpPost]
        public JsonResult Create(MainPageVM model)
        {
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileNameWithExtension = Path.GetFileName(file.FileName);
                    var fileNameOnly = Path.GetFileNameWithoutExtension(file.FileName);
                    string RootPath = Server.MapPath("~/Images/");
                    if (!Directory.Exists(RootPath))
                    {
                        Directory.CreateDirectory(RootPath);
                    }
                    var unique = new Guid();
                    var path = Path.Combine(RootPath, fileNameOnly + unique + Path.GetExtension(file.FileName));
                    file.SaveAs(path);
                    model.PhotoPath = "Images/" + fileNameOnly + unique + Path.GetExtension(file.FileName);

                }



            }

            var data = "SP_AddMainPage".ExecuParamsSqlOrStored(false, "Title".KVP(model.Title), "Description".KVP(model.Description),
                "PhotoPath".KVP(model.PhotoPath), "type".KVP("news"), "Brief".KVP(model.Brief), "IsActive".KVP(model.ISActive), "ID".KVP(model.ID)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "تم الحفظ بنجاح", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + "لم يتم الحفظ ", JsonRequestBehavior.AllowGet);
        }


        public ActionResult Edit(int id = 0)
        {
            var model = "SP_SelectMainPageById".ExecuParamsSqlOrStored(false, "ID".KVP(id)).AsList<MainPageVM>();
            if (model == null)
            {
                return HttpNotFound();
            }
            return PartialView("~/Areas/Admin/Views/MNews/Create.cshtml", model.FirstOrDefault());
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            MainPageVM obj = new MainPageVM();
            obj.ID = id;
            return PartialView("~/Areas/Admin/Views/MNews/Delete.cshtml", obj);
        }


        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            var data = "SP_DeleteMainPage".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "تم الحذف بنجاح", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + "لم يتم الحذف", JsonRequestBehavior.AllowGet);
        }
    }
}
 

SchoolSystem.web/Areas/Admin/Controllers/MServicesController.cs
using SchoolSystem.Core;
using SchoolSystem.Core.VM;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolSystem.web.Areas.Admin.Controllers
{
    public class MServicesController : Controller
    {
        public ActionResult Index1()
        {
            return View();
        }

        public ActionResult Search()
        {

            var model = "SP_GetAllServices".ExecuParamsSqlOrStored(false).AsList<MainPageVM>();
            return View(model);
        }


        public ActionResult Create()
        {
            MainPageVM Obj = new MainPageVM();
            return PartialView("~/Areas/Admin/Views/MServices/Create.cshtml", Obj);
        }
        [HttpPost]
        public JsonResult Create(MainPageVM model)
        {
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileNameWithExtension = Path.GetFileName(file.FileName);
                    var fileNameOnly = Path.GetFileNameWithoutExtension(file.FileName);
                    string RootPath = Server.MapPath("~/Images/");
                    if (!Directory.Exists(RootPath))
                    {
                        Directory.CreateDirectory(RootPath);
                    }
                    var unique = new Guid();
                    var path = Path.Combine(RootPath, fileNameOnly + unique + Path.GetExtension(file.FileName));
                    file.SaveAs(path);
                    model.PhotoPath = "Images/" + fileNameOnly + unique + Path.GetExtension(file.FileName);

                }



            }

            var data = "SP_AddMainPage".ExecuParamsSqlOrStored(false, "Title".KVP(model.Title), "Description".KVP(model.Description),
                "PhotoPath".KVP(model.PhotoPath), "type".KVP("service"), "Brief".KVP(model.Brief), "IsActive".KVP(model.ISActive), "ID".KVP(model.ID)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "تم الحفظ بنجاح", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + "لم يتم الحفظ ", JsonRequestBehavior.AllowGet);
        }


        public ActionResult Edit(int id = 0)
        {
            var model = "SP_SelectMainPageById".ExecuParamsSqlOrStored(false, "ID".KVP(id)).AsList<MainPageVM>();
            if (model == null)
            {
                return HttpNotFound();
            }
            return PartialView("~/Areas/Admin/Views/MServices/Create.cshtml", model.FirstOrDefault());
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            MainPageVM obj = new MainPageVM();
            obj.ID = id;
            return PartialView("~/Areas/Admin/Views/MServices/Delete.cshtml", obj);
        }


        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            var data = "SP_DeleteMainPage".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "تم الحذف بنجاح", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + "لم يتم الحذف", JsonRequestBehavior.AllowGet);
        }
    }
}

SchoolSystem.web/Areas/Admin/Views/MServices/Create.cshtml
@model SchoolSystem.Core.VM.MainPageVM
@{
    Layout = null;

}


@using (Html.BeginForm("Create", "MNews", new { area = "Admin" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @*@<div id="myModalAdd" class="modal fade" role="dialog">*@
    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content" style="width: 900px;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">اضافه او تعديل &nbsp; &nabla; </h4>
            </div>
            <div class="modal-body" style="width :900px;">
                <div class="panel">
                    @*<div class="panel-heading">
                            <span class="panel-title hidden-xs">@BasicInputRes.CustomerActivitiesDetails</span>
                        </div>*@
                    <div class="panel-body p25 pb5">
                        <div class="tab-content pn br-n admin-form">
                            <div id="tab1_1" class="tab-pane active">
                                <div class="row">
                                    <div class="col-md-2">
                                        @Html.HiddenFor(model => model.ID)
                                        <label>    @SchoolSystem.Localiztion.AgentResource.Address  </label>
                                    </div>
                                    <div class="col-md-4">
                                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @placeholder = "العنوان ....." }, id = "Title" })
                                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                        @*@Html.EditorFor(model => model.NameAr, new { htmlAttributes = new { @class = "form-control input-circle" } })*@
                                    </div>
                                    <div class="col-md-2">
                                        <label>    @SchoolSystem.Localiztion.AgentResource.Description  </label>
                                    </div>
                                    <div class="col-md-4">
                                        @Html.EditorFor(model => model.Brief, new { htmlAttributes = new { @class = "form-control", @placeholder = "العنوان ....." }, id = "Brief" })
                                        @Html.ValidationMessageFor(model => model.Brief, "", new { @class = "text-danger" })
                                        @*@Html.EditorFor(model => model.NameAr, new { htmlAttributes = new { @class = "form-control input-circle" } })*@
                                    </div>


                                </div>
                                <br />
                                <div class="row">
                                    <div class="col-md-2">
                                        <label>    @SchoolSystem.Localiztion.AgentResource.Description  </label>
                                    </div>
                                    <div class="col-md-10">

                                        <textarea class="form-control" id="Description" name="Description" placeholder="الوصف" >@Model.Description</textarea>
                                        @*@Html.TextAreaFor(model => model.Description, new { @class = "form-control", @placeholder = "الوصف .....", @id = "Description" ,@name= "Description" })*@
                                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                        @*@Html.EditorFor(model => model.NameAr, new { htmlAttributes = new { @class = "form-control input-circle" } })*@
                                    </div>


                                </div>
                                <br />
                                <div class="row">
                                   


                                </div>

                                <br />
                                <div class="row">
                                 
                                

                                    <div class="col-md-2">
                                        <label>    @SchoolSystem.Localiztion.AgentResource.Case  </label>
                                    </div>
                                    <div class="col-md-4">

                                        <select class="form-control list-box tri-state" id="IsActive" name="IsActive">


                                            <option value="false">يعرض</option>
                                            <option value="false">لا يعرض</option>




                                        </select>  @Html.ValidationMessageFor(model => model.ISActive, "", new { @class = "text-danger" })
                                    </div>

                                </div>
                                
                                <br />

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            @Html.TextBox("file", null, new { @id = "input-1700", @type = "file", @class = "file-loading", @accept = "image/*" })
                                            <script>
                                                $("#input-1700").fileinput({
                                                    maxFileCount: 1,
                                                    allowedFileExtensions: ["jpg", "png", "gif"],
                                                    browseLabel: " إضغط لإختيار صورة ..",
                                                    browseIcon: "<i class=\"glyphicon glyphicon-picture\"></i> ",
                                                    browseClass: "btn btn-primary btn-block",
                                                    showCaption: false,
                                                    showRemove: false,
                                                    showUpload: false
                                                });
                                            </script>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">

                                    </div>
                                    <div class="col-md-3">
                                        <input type="button" value="حفظ" class="btn yellow Saveee" onclick="Save()" />
                                        <button type="button" class="btn btn-default" data-dismiss="modal">الغاء</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="modal fade" id="myModalAddEditDesign" role="dialog" data-backdrop="static"></div>

    @*</div>*@
}



<script>
    $(document).ready(function () {
        $("input[type=text]").addClass("gui-input");
    });
</script>
@*<script src="~/ckeditor/ckeditor.js"></script>
<script>
    CKEDITOR.replace('Description');
</script>*@

SchoolSystem.web/Areas/Admin/Views/MServices/Delete.cshtml
@model SchoolSystem.Core.VM.MainPageVM


    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"> حذف  </h4>
            </div>
            <div class="modal-body" style="width :900px;">
          
                <h4 class="modal-title"> هل تريد الحذف ?????? </h4>
                <div class="row">
                    <div class="col-md-3">
                        <input type="button" value="حذف" class="btn yellow Saveee" onclick="DeleteRow(@Model.ID)" />
                        <button type="button" class="btn btn-default" data-dismiss="modal">الغاء</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

SchoolSystem.web/Areas/Admin/Views/MServices/Index1.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div id="content">

    <!-- widget grid -->
    <section id="widget-grid" class="">
        @*<div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <br />
                    <h4 class="page-title"><a href="~/HomeAdmin/index">الرئسيه</a>--  </h4>  <h4 class="page-title"> اعدادات الصفحه الرئسية</h4>
                    <br />

                </div>
            </div>
        </div>*@
        <!-- START ROW -->
        <div class="row">

            <!-- NEW COL START -->
            <article class="col-sm-12 col-md-12 col-lg-12">

                <!-- Widget ID (each widget will need unique ID)-->
                <div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
                    <input type="button" id="AddNew" onclick="Create()" class="btn yellow " value="اضافه جديد" />
                    <!-- widget div-->
                    <div>

                        <!-- widget edit box -->
                        <div class="jarviswidget-editbox">
                            <!-- This area used as dropdown edit box -->

                        </div>
                        <!-- end widget edit box -->
                        <!-- widget content -->
                        <div class="widget-body no-padding">

                            <form class="smart-form">
                                <br />
                                <div id="SearchTableContainer"></div>
                            </form>

                        </div>
                        <!-- end widget content -->

                    </div>
                    <!-- end widget div -->

                </div>
                <!-- end widget -->

            </article>
            <!-- END COL -->

        </div>

        <!-- END ROW -->
    </section>
    <!-- end widget grid -->

    <div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>

</div>
@section scripts {
    <script src="~/Areas/Admin/Script/MServices.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            MServices.init();

        })

    </script>
}

SchoolSystem.web/Areas/Admin/Views/MServices/Search.cshtml
@model IEnumerable<SchoolSystem.Core.VM.MainPageVM>

@{ 
    Layout = null;
}
<div class="row">
    <div class="col-12">
        <div class="card-box table-responsive">
            <table class="table table-hover table-bordered datatable" width="100%">
                <thead>
                    <tr>
                        <th>@SchoolSystem.Localiztion.AgentResource.ID</th>
                        <th>@SchoolSystem.Localiztion.AgentResource.Address </th>
                        <th>@SchoolSystem.Localiztion.AgentResource.Image </th>
                        <th>@SchoolSystem.Localiztion.AgentResource.Case </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.ID</td>
                        <td>@item.Title</td>
                        <td> <img src="~/@item.PhotoPath" style="width:150px;height:150px;" /></td>
                        @if (item.ISActive == true)
                        {
                        <td>يعرض</td>
                        }
                        else
                        {
                        <td>لا يعرض</td>
                        }
                        <td>
                            <div class="btn-group display-inline pull-right text-align-center hidden-tablet">
                                <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-cog fa-lg"></i>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-xs pull-left">
                                    <li class="text-align-center">
                                        <button type="button" class="btn btn-success   waves-effect waves-light m-b-0" id="btnUpdate" onclick="Edit(@item.ID)">تعديل</button>
                                    </li>
                                    <li class="divider"></li>
                                    <li class="text-align-center">
                                        <button type="button" class="btn btn-danger  waves-effect waves-light m-b-0" onclick="Delete(@item.ID)"> حذف</button>
                                    </li>
                                    <li class="divider"></li>
                                    <li class="text-align-center">
                                        <a href="javascript:void(0);" class="btn btn-warning waves-effect waves-light m-b-0" aria-hidden="true">الغاء</a>
                                    </li>
                                </ul>
                            </div>
                        </td>

                    </tr>
                    }
                </tbody>
            </table>
        </div>
        </div>
    </div>
        <script type="text/javascript">
            $(function () {
                $('.datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            });


        </script>